DROP TABLE MEMBER4 IF EXISTS;
DROP TABLE PHONE IF EXISTS;
DROP SEQUENCE member2_seq IF EXISTS;
DROP SEQUENCE phone_seq IF EXISTS;

CREATE TABLE MEMBER4(
	seq number(10) PRIMARY KEY,
	name varchar2(50) DEFAULT NULL
);

CREATE TABLE PHONE(
	seq number(10) PRIMARY KEYL,
	member_id number(10) DEFAULT NULL,
	no VARCHAR2(20) DEFAULT NULL
);

CREATE SEQUENCE member4_seq
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1;
	
CREATE SEQUENCE phone_seq
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1;
